config/routes.rb
Wheresmybus::Application.routes.draw do  
  root :to => 'application#index'

  resources :busses do
    member do
      get 'path'
    end
    collection do
      post "update_nicknames"
      get "confirm_destroy_all"
      delete "destroy_all"
    end
  end

  devise_for :admins

  devise_for :users, :controllers=>{:confirmations=>"users_confirmations"}, :skip=>:registrations do
    put "/users/confirmations", :to=>"users_confirmations#update", :as=>:update_user_confirmation
  end
  as :user do
    scope "/users" do
      resource :profile, :controller=>"registrations", :only=>[:edit,:update] do
        get "edit_password", :as=>"edit_password_of"
      end
    end
  end
  
  resources :users do
    collection do
      get "confirm_destroy_all"
      delete "destroy_all"
    end
  end
  
  get "/welcome" => "users#splash"
  

end

app/controllers/busses_controller.rb
class BussesController < ApplicationController
  #TODO: before_filter :auth_user_or_admin
  layout nil
  layout "application", :only=>[:destroy_all, :confirm_destroy_all]
  
  before_filter :auth_user_or_admin!
  before_filter :authenticate_admin!, :only=>[:destroy_all, :confirm_destroy_all]
  
  def index
    if user_signed_in?
      @busses = fetch_bus_locations(current_user.busses)
    else #admin
      @busses = [] #$zonar.fleet["assetlist"]["assets"].map {|b| {:properties=>{'fleet'=>b['fleet']}} }#fetch_all_bus_locations
    end
  end
  
  def show
    if user_signed_in?
      if bus = current_user.busses.find_by_fleet_id(params[:id])
        @bus = fetch_bus_locations([bus]).first
      end
    else #admin can view all
      @bus = fetch_bus_locations([Bus.new(:fleet_id=>params[:id])]).first
    end
    render :partial => 'details' if params[:details]
  end
  
  def path
    respond_to do |format|
      format.json  { render :json => fetch_bus_path(params[:id]) }
    end
  end
  
  def update_nicknames
    @user = current_user
    allowable_busses = params[:user][:busses_attributes].select {|i,b| b["id"].present?}
    respond_to do |format|
      if @user.update_attributes(:busses_attributes=>allowable_busses)
        @user.save
        format.html { render :partial => 'success' }
      else
        @fleet_ids = $zonar.fleet["assetlist"]["assets"].map {|a| a["fleet"]}
        format.html { render :partial => 'fail' }
      end
    end
  end
  
    #get
  def confirm_destroy_all
  end
  
  #delete
  def destroy_all
    Bus.destroy_all
    respond_to do |format|
      format.html { redirect_to(users_path, :notice => 'All busses were successfully deleted.') }
      format.xml  { head :ok }
    end
  end

  private
  def fetch_bus_locations(busses)
    busses.map do |b|
      location = $zonar.bus(b.fleet_id)
      next unless location.keys.include? 'currentlocations'
      time = location['currentlocations']['asset']['time']
      location['currentlocations']['asset']['time'] = Time.parse(time)
      {
        :type => "Feature",
        :geometry => {
          :type => "Point",
          :coordinates => [
            location['currentlocations']['asset'].delete('long'),
            location['currentlocations']['asset'].delete('lat')
          ]
        },
        :properties => location['currentlocations']['asset'].merge({"nickname" => b.nickname})
      }
    end.compact
  end
  
  def fetch_bus_path(bus)
    path = $zonar.path(bus)
    if path['pathevents']['assets']
      coordinates = $zonar.path(bus)['pathevents']['assets'][0]['events'].map do |location|
        [ location['lng'], location['lat'] ]
      end
      return {
        :type => "LineString",
        :coordinates => coordinates
      }
    else
      return {}
    end
  end

  def auth_user_or_admin!
    authenticate_user! unless user_signed_in? or admin_signed_in?
  end
end

app/helpers/busses_helper.rb
module BussesHelper
end

app/views/busses/_details.html.erb
<div data-role="page"> 
	<div data-role="header" data-theme="e" data-position="inline"> 
		<h1>Bus Details</h1> 
	</div> 

	<div data-role="content" data-theme="e">
	  <%- if @bus %>
  		<h1><%= @bus[:properties]['fleet'] %></h1> 
  		<p>Last seen: <%= time_ago_in_words(@bus[:properties]['time']) %> ago</p> 
    <%- else %>
      <h1>Could not fetch bus info</h1>
    <%- end %>
	</div> 
</div>

app/views/busses/_fail.html.erb
<div data-role="page" data-theme="c"> 
 
	<div data-role="header" data-theme="e" data-backbtn="false"> 
		<h1>Failed to update</h1> 
	</div>
 
	<div data-role="content" data-theme="c"> 
		
		<p>Your nicknames were <strong>not</strong>saved. Please try again</p> 
			
			<a data-role="button" class="go_home">Go Back</a>
 
	</div>
</div>

app/views/busses/_faq.html.erb
<div data-role="collapsible" data-collapsed="true">
	<h3>What is this service?</h3>
	<p>Where’s My School Bus allows guardians of Boston Public School students to see on a map where their children’s school buses are in the city.</p>
</div>
<div data-role="collapsible" data-collapsed="true">
	<h3>Is the location of the bus on the map always accurate?</h3>
	<p>No.</p>
  <p>The location of the bus on the map comes from the school bus’s GPS (Global Positioning System) device.  For a number of reasons, that device can occasionally fail to work.  Consequently, the school bus will occasionally be in a different location than the one presented on the map.</p>
  <p>Occasionally, BPS Transportation must make bus substitutions due to repairs, route changes, or weather disruptions. If a different bus was substituted for your student’s normally assigned bus, you may not see the location of the bus your student is actually riding.</p>
  <p>If you need to confirm a bus location, you can all the BPS Transportation Hotline at <a href="tel:+1-617-635-9520">(617) 635-9520</a>.  The hotline is available Monday through Friday: 8:30 a.m. - 5:00 p.m.</p>
</div>
<div data-role="collapsible" data-collapsed="true">
  <h3>My student is supposed to be on a bus that hasn’t moved recently on the map. Why is that?</h3>
  <p>There are several reasons why a bus may not move on the map.</p>
  <p>Occasionally, BPS Transportation must make bus substitutions due to repairs, route changes, or weather disruptions. If a different bus was substituted for your student’s assigned bus, you may instead see the stationary location of your student’s normally assigned bus, rather that the bus he or she is actually riding.</p>
  <p>Additionally, sometimes the GPS (Global Positioning System) device on a bus can fail to work. If this occurs, the school bus may not appear on the map, or may appear in an inaccurate location. Rest assured that BPS Transportation is working as quickly as possible to restore GPS functionality.</p>
  <p>If you need to confirm a bus location, you can all the BPS Transportation Hotline at <a href="tel:+1-617-635-9520">(617) 635-9520</a>.  The hotline is available Monday through Friday: 8:30 a.m. - 5:00 p.m.</p>
</div>
<div data-role="collapsible" data-collapsed="true">
  <h3>What is the black line on the map behind the bus?</h3>
  <p>The black line behind a bus shows its previous location over the past 30 minutes. This line allows you to see a bus’s recent route and approximate rate of travel. If the bus has not moved in the last 30 minutes, you will not see a line on the map.</p>
</div>
<div data-role="collapsible" data-collapsed="true">
  <h3>How do I sign up to see a specific bus?</h3>
  <p>If you are the guardian of a BPS student, you can sign up by calling the BPS Transportation Hotline at <a href="tel:+1-617-635-9520">(617) 635-9520</a>.  The hotline is available Monday through Friday: 8:30 a.m. - 5:00 p.m. 
  You will need to provide the hotline operator with the following pieces of information: XYZ etc</p>
</div>
<div data-role="collapsible" data-collapsed="true">
  <h3>What if I don’t know my student’s bus number?</h3>
  <p>The staff of the BPS Transportation Hotline can tell you what your student’s bus number is.  The BPS Transportation Hotline is at <a href="tel:+1-617-635-9520">(617) 635-9520</a>.  The hotline is available Monday through Friday: 8:30 a.m. - 5:00 p.m.</p>
</div>
<div data-role="collapsible" data-collapsed="true">
  <h3>How many buses can I sign up to track?</h3>
  <p>This application is a service only for the immediate guardians of BPS parents.  You will be able to track all of the buses assigned to the students for whom you are the guardian, but only those buses.</p>
</div>
<div data-role="collapsible" data-collapsed="true">
  <h3>Who else can see what bus numbers I signed up for?</h3>
  <p>BPS Transportation Staff are the only people that can see that information.  Your name, password and bus numbers associated with your account are otherwise private and will not be shared.</p>
</div>
<div data-role="collapsible" data-collapsed="true">
  <h3>What if my student’s bus or bus number changes either permanently or for a particular day?</h3>
  <p>If your student will be taking a different bus to or from school on a permanent basis, simply call the Transportation Hotline at <a href="tel:+1-617-635-9520">(617) 635-9520</a> and ask for them to change the bus you can see in this application.  The hotline is available Monday through Friday: 8:30 a.m. - 5:00 p.m.</p>
  <p>If your student will riding a different bus for just one day, we will be unable to update the change for that day to allow you to track the new bus.</p>
</div>
<div data-role="collapsible" data-collapsed="true">
  <h3>What if I forget my password?</h3>
  <p>You can reset your password by going to the “Sign-In” page on the application and clicking “Forgot your password?”</p>
  <p>Alternatively, you can call the BPS Transportation Hotline at <a href="tel:+1-617-635-9520">(617) 635-9520</a>, who can delete and recreate your account.  The hotline is available Monday through Friday: 8:30 a.m. - 5:00 p.m.</p>
</div>
<div data-role="collapsible" data-collapsed="true">
  <h3>Do I have to sign up each year?</h3>
  <p>Yes.  At the beginning of every school year, you will have to sign up again, by calling the BPS Transportation Hotline. The BPS Transportation Hotline is at <a href="tel:+1-617-635-9520">(617) 635-9520</a>.  The hotline is available Monday through Friday: 8:30 a.m. - 5:00 p.m.</p>
</div>
<div data-role="collapsible" data-collapsed="true">
  <h3>Any other questions?</h3>
  <p>Call the BPS Transportation Hotline at <a href="tel:+1-617-635-9520">(617) 635-9520</a>.  The hotline is available Monday through Friday: 8:30 a.m. - 5:00 p.m.</p>
</div>

app/views/busses/_help.html.erb
<div data-role="page" data-theme="b" id="help"> 
  <div data-role="header">
    <h1>Help</h1>
    <a href="#home" data-role="button" data-icon="arrow-l" data-transition="reverse slide">Buses</a>
  </div>
  <div data-role="content" data-theme="c">
    <%= render :partial => 'faq' %>
  </div>
</div>

app/views/busses/_success.html.erb
<div data-role="page" data-theme="c"> 
 
	<div data-role="header" data-theme="e" data-backbtn="false"> 
		<h1>Updated successfully!</h1> 
	</div>
 
	<div data-role="content" data-theme="c"> 
		
			<p>Your nicknames were saved successfully.</p>
			
			<a data-role="button" class="go_home">Go Back</a>
 
	</div>
</div>

app/views/busses/confirm_destroy_all.html.erb
<span class="warning">Warning: this will remove all the buses from all the users in the database, and is NOT reversible.</span>
<div class="warning_confirm"><%= link_to 'I understand and want to delete all buses »',destroy_all_busses_path, :confirm => 'Are you really sure? This cannot be undone.', :method => :delete, :class => "warning_confirm_text" %></div>

app/views/busses/index.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
  <head>
    <!-- Change this if you want to allow scaling -->
    <meta name="viewport" content="width=device-width, minimum-scale=1, maximum-scale=1">
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta names="apple-mobile-web-app-status-bar-style" content="black-translucent" />
    <link rel="stylesheet"  href="stylesheets/jquery.mobile-1.0a4.1.min.css" />
    <link rel="stylesheet"  href="stylesheets/mobile.css" />
    <script src="javascripts/json2.js"></script>
    <script src="javascripts/jquery.min.js"></script>
    <script src="javascripts/jquery.mobile-1.0a4.1.min.js"></script>       
    <script src="javascripts/mustache.js" type="text/javascript" charset="utf-8"></script>
    <script src="http://maps.google.com/maps/api/js?sensor=true"> </script> 
    <script src="javascripts/geojson-to-google-maps.js"></script>  
    <script type="text/javascript">
      var busses = {}
      $.each(JSON.parse("<%= @busses.to_json.html_safe.gsub('"', '\"') %>"), function(i, bus) {
        busses[bus.properties.fleet] = bus;
      });
      $(function() {
        $('#map').live('pageshow', function (event, ui) {
          target = $(event.currentTarget).attr('fleet');
          showMap(busses[target], event.currentTarget);
        });
        $('.go_home').live('click', function(e) {
          window.location = "/";
        })
        $('#bus_refresh').live('click', function(e) {
          showBusOnMap(currentBus.feature);
        })
      })
    </script>
    <script src="javascripts/busmap.js" type="text/javascript"></script>
  </head>
  <body>
    <div data-role="page" data-theme="b" id="home"> 
      <div data-role="header">
        <h1>My Buses</h1>
        <%= link_to "Sign Out", destroy_user_session_path, :"data-ajax"=>"false" %>
        <% if @busses.size > 0 -%>
          <a href="#edit_names" data-role="button" data-icon="delete">Edit Names</a>
        <% end -%>
      </div>
      <div data-role="content"> 
        <% if @busses.size > 0 -%>
          <ul data-role="listview" data-inset="true" data-theme="c" data-dividertheme="b"> 
            <li data-role="list-divider">Buses</li>
      			<%- @busses.each do |bus| %>
        			<li>
        			  <a href="/busses/<%= bus[:properties]['fleet'] %>">
        			    <%= bus[:properties]['nickname'] %>
        			  </a>
        			</li> 
      			<%- end %>
    			</ul>
        <% else -%>
          <p>You haven't been granted access to view any buses yet.</p>
        <% end -%>
  		  <ul data-role="listview" data-inset="true" data-theme="c" data-dividertheme="b"> 
          <li>
            <a href="#help">
              Help
            </a>
          </li>
        </ul>
  		</div>
    </div>
    
    <% if @busses.size > 0 -%>
      <div data-role="page" data-theme="b" id="edit_names"> 
        <div data-role="header">
          <h1>Edit Bus Names</h1>
        </div>
        <div data-role="content"> 
          <%= form_for current_user, :url => update_nicknames_busses_path, :html=>{:method=>:post} do |f| %>
            <fieldset> 
              <%= f.fields_for :busses do |bf| %>
                <div data-role="fieldcontain">
                  <%= bf.label :nickname, "#{bf.object.fleet_id}'s nickname" %>
                  <%= bf.text_field :nickname %>
                </div>
              <% end %>
              <button type="submit" data-theme="a" name="submit" value="true">Update Names</button> 
            </fieldset> 
          <% end %>
    		</div>
      </div>
    <% end -%>
    
    <%= render :partial => 'help' %>
    
  </body>
</html>

app/views/busses/show.html.erb
<div data-role="page" data-theme="c" id="map" fleet="<%= @bus[:properties]['fleet'] %>">    
  <div data-role="header">
    <h1>Bus Location</h1>
    <a id="bus_refresh" data-icon="refresh" class="ui-btn-right">Refresh</a>
  </div>
  <div data-role="content">
    <div id="map_canvas"></div>
  </div>
</div>