config/routes.rb
Wheresmybus::Application.routes.draw do  
  root :to => 'application#index'

  resources :busses do
    member do
      get 'path'
    end
    collection do
      post "update_nicknames"
      get "confirm_destroy_all"
      delete "destroy_all"
    end
  end

  devise_for :admins

  devise_for :users, :controllers=>{:confirmations=>"users_confirmations"}, :skip=>:registrations do
    put "/users/confirmations", :to=>"users_confirmations#update", :as=>:update_user_confirmation
  end
  as :user do
    scope "/users" do
      resource :profile, :controller=>"registrations", :only=>[:edit,:update] do
        get "edit_password", :as=>"edit_password_of"
      end
    end
  end
  
  resources :users do
    collection do
      get "confirm_destroy_all"
      delete "destroy_all"
    end
  end
  
  get "/welcome" => "users#splash"
  

end

app/controllers/users_confirmations_controller.rb
#this code taken from https://github.com/plataformatec/devise/wiki/How-To:-Override-confirmations-so-users-can-pick-their-own-passwords-as-part-of-confirmation-activation

class UsersConfirmationsController < Devise::ConfirmationsController
  skip_before_filter(:authenticate_user!)
  # PUT /resource/confirmation
  def update
    @confirmable = User.find_or_initialize_with_error_by(:confirmation_token,params[:confirmation_token])

    if @confirmable.new_record?
      #if the token doesn't exist, they're already confirmed, or they never existed. what's the best way to deal?
      flash[:notice]="invalid confirmation token"
      redirect_to :action=>:new 
      return false;
    end
      
    if @confirmable.confirmed?
      #this should be impossible, really.
      raise "you already confirmed, yo"
      return false
    end
     
    @confirmable.update_attributes(params[:user]) #update all their attributes, including password & profile info
    if @confirmable.valid?
      do_confirm
    else
      do_show
    end

  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    @confirmable = User.find_or_initialize_with_error_by(:confirmation_token,params[:confirmation_token])

    if @confirmable.new_record?
      #if the token doesn't exist, they're already confirmed, or they never existed. what's the best way to deal?
      flash[:notice]="invalid confirmation token"
      redirect_to :action=>:new 
      return false;
    end
    
    if @confirmable.confirmed?
      #this should be impossible, really.
      raise "you already confirmed, yo"
      return false
    end
    
    #CANNOT confirm off of a show. must put back with a form
    do_show
  end
  
  protected

  def do_show
    @confirmation_token = params[:confirmation_token]
    @requires_password = true
    self.resource = @confirmable
    render_with_scope :show
  end

  def do_confirm
    @confirmable.confirm!
    set_flash_message :notice, :confirmed
    sign_in_and_redirect(resource_name, @confirmable)
  end
end

app/views/users_confirmations/new.html.erb
<h2>Resend confirmation instructions</h2>

<%= form_for(resource, :as => resource_name, :url => confirmation_path(resource_name), :html => { :method => :post }) do |f| %>
  <%= devise_error_messages! %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.submit "Resend confirmation instructions" %>
  </div>
<% end %>

<div class="user_links">
  <%= render :partial => "devise/shared/links" %>
</div>

app/views/users_confirmations/show.html.erb
<h2>Activate Your Account</h2>
<% form_for @confirmable, :url => update_user_confirmation_path, :html => {:method => 'put'}, :id => 'activation-form' do |f| %>
  
  <% if @confirmable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@confirmable.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @confirmable.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <fieldset>
    <legend><%= @confirmable.email %></legend>
    
    <div class="field">
      <%= f.label :first_name %><br />
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :last_name %><br />
      <%= f.text_field :last_name %>
    </div>
    
    <div class="field">
      <%= f.label :password,'Password' %><br />
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation,'Confirm Password' %><br />
      <%= f.password_field :password_confirmation %>
    </div>
    <%= hidden_field_tag :confirmation_token,@confirmation_token %>
    <p><%= f.submit "Activate" %></p>
  </fieldset>
<% end %>