config/routes.rb
Wheresmybus::Application.routes.draw do  
  root :to => 'application#index'

  resources :busses do
    member do
      get 'path'
    end
    collection do
      post "update_nicknames"
      get "confirm_destroy_all"
      delete "destroy_all"
    end
  end

  devise_for :admins

  devise_for :users, :controllers=>{:confirmations=>"users_confirmations"}, :skip=>:registrations do
    put "/users/confirmations", :to=>"users_confirmations#update", :as=>:update_user_confirmation
  end
  as :user do
    scope "/users" do
      resource :profile, :controller=>"registrations", :only=>[:edit,:update] do
        get "edit_password", :as=>"edit_password_of"
      end
    end
  end
  
  resources :users do
    collection do
      get "confirm_destroy_all"
      delete "destroy_all"
    end
  end
  
  get "/welcome" => "users#splash"
  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :busses
  
  cattr_reader :per_page
  @@per_page = 20

  accepts_nested_attributes_for :busses, :allow_destroy=>true, :reject_if=>lambda {|b| b["fleet_id"].blank? && b["id"].blank?}
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :confirmable, :registerable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :busses_attributes, :student_ids
  
  validates_presence_of :first_name, :if=>:has_signed_in?
  validates_presence_of :last_name, :if=>:has_signed_in?
  validates_presence_of :password, :if=>:password_required?
  validates_presence_of :password_confirmation, :if=>:password_required?
  
  private
  def password_required?
    sign_in_count > 0 && ((confirmation_sent_at? && encrypted_password.blank?) || password.present? || password_confirmation.present?)
  end
  def has_signed_in?
    sign_in_count > 0
  end
end

app/controllers/users_controller.rb
require 'csv'
class UsersController < ApplicationController
  before_filter :authenticate_admin!, :except => [:splash]
  
  def index
    @users = if params[:q]
      @q = params[:q]
      User.where("email like :q or first_name like :q or last_name like :q",:q=>"%#{params[:q].downcase}%")
    else
      User.all
    end

    respond_to do |format|
      format.html do
        @users = @users.paginate :page=>params[:page]
        render
      end
      format.xml  { render :xml => @users }
      format.csv do
        prefix = @q.present? ? @q.gsub(/\s+/,'_') : "all"
        render_csv(prefix+"_emails.csv") do |csv|
          @users.each {|u| csv << [u.email]}
        end
      end
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new
    @user.busses_attributes = {"0"=>{"fleet_id"=>"none"}} # add a temp new one
    @fleet_ids = $zonar.fleet["assetlist"]["assets"].map {|a| a["fleet"]}
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    @fleet_ids = $zonar.fleet["assetlist"]["assets"].map {|a| a["fleet"]}
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(users_path, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        @fleet_ids = $zonar.fleet["assetlist"]["assets"].map {|a| a["fleet"]}
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        @fleet_ids = $zonar.fleet["assetlist"]["assets"].map {|a| a["fleet"]}
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_path, :notice => 'User was successfully deleted.') }
      format.xml  { head :ok }
    end
  end
  
  #get
  def confirm_destroy_all
  end
  
  #delete
  def destroy_all
    User.destroy_all
    respond_to do |format|
      format.html { redirect_to(users_path, :notice => 'All users were successfully deleted.') }
      format.xml  { head :ok }
    end
  end
  
  private
  def render_csv(filename)
    csv_data = CSV.generate {|csv| yield csv}
    send_data csv_data, :type=> "text/csv", :filename=> filename, :disposition => "attachment"
  end
end

app/views/users/_form.html.erb
<div id="content" class="page-content clear-block">
  <h1>User Information</h1>
  <div id="content-wrapper">
    <div>
      <div class="form form-layout-default clear-block">
        <%= nested_form_for(@user) do |f| %>
          <% if @user.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

              <ul>
              <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <div class="column-wrapper clear-block">
            <fieldset class="menu-item-form fieldset titled collapsible collapsed tao-processed">
              <legend><span class="fieldset-title"><a href="#fieldset" class="active">User Details</a></span></legend>
              <div class="fieldset-content clear-block ">
                <div class="form-item form-item-labeled" id="edit-menu-link-title-wrapper">
                  <%= f.label :email %><br />
                  <%= f.text_field :email, {:class => "form-text fluid"}%>
                  <div class="description">
                    What is the e-mail address of the user? They will use this to log in.
                  </div>
                </div>
                <div class="form-item form-item-labeled" id="edit-menu-link-title-wrapper">
                  <%= f.label :student_ids %><br />
                  <%= f.text_field :student_ids, {:class => "form-text fluid"}%>
                  <div class="description">
                    Which student ID(s) is/are this user following?
                  </div>
                </div>
              </div>
            </fieldset>
            <fieldset class="menu-item-form fieldset titled collapsible collapsed tao-processed">
              <legend><span class="fieldset-title"><a href="#fieldset" class="active">Buses</a></span></legend>
              <div class="fieldset-content clear-block ">
              <%= f.fields_for :busses do |bf| %>
                  <div class="form-item form-item-labeled" id="edit-menu-link-title-wrapper">
                    <%= bf.label :fleet_id, "Bus ID" %><br />
                    <%= bf.select :fleet_id, [nil]+@fleet_ids, {}, {:class => "form-select"} %>
                    <div class="description">
                      Choose a bus that this user is allowed to see the location of.
                    </div>
                    <%= bf.link_to_remove "Remove This Bus" %>
                  </div>
              <%end%>
              <%= f.link_to_add "Add a new Bus", :busses %>
            </div>                      
            </fieldset>
            <div class="buttons">
              <%= f.submit "Submit", {:class => "form-submit"} %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="user_links">
    <%= link_to '< All Users', users_path, {:class => "button"} %>  
  </div>
</div>

app/views/users/confirm_destroy_all.html.erb
<span class="warning">Warning: this will delete all the users in the database and is NOT reversible.</span>
<div class="warning_confirm"><%= link_to 'I understand and want to delete all users »', destroy_all_users_path, :confirm => 'Are you really sure? This cannot be undone.', :method => :delete, :class => "warning_confirm_text" %></div>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<h2>List of Users</h2>
<%= link_to 'New User', new_user_path, {:class => "primary button"} %>
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Student ID(s)</th>    
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @users.each do |user| {:class => "sign_in_out button dark"} %> 
  <tr>
    <td><%= "#{user.last_name}, #{user.first_name}" %></td>
    <td><%= user.email %></td>
    <td><%= user.student_ids %></td>
    <td><%= link_to 'Edit Account', edit_user_path(user) %></td>
    <td><%= link_to 'Delete Account', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
<%= will_paginate @users %>
<%= form_for users_path, :html=>{:method=>:get} do |f|%>
  <div class="search_box field">
    <%= f.label :search_box, "Search: "%>
    <%= f.text_field :search_box,:name=>"q" %>	
  </div>
<%end%>
</table>
<div class="user_links">
	<%= link_to 'Export as CSV', users_path(:format=>"csv", :q=>@q), :class => "export_link" %>  |  
	<%= link_to 'Delete All Users', confirm_destroy_all_users_path, :class => "delete_link" %>  |  
	<%= link_to 'Delete All Buses', confirm_destroy_all_busses_path, :class => "delete_link" %>
</div>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<div id="edit_user_page" class="user_page">
  <div class="user_links">
    <%= link_to 'Edit Details', edit_user_path(@user), {:class => "button"} %>
    <%= link_to 'Go Back', users_path, {:class => "button"} %>
  </div>
</div>

app/views/users/splash.html.erb
<% content_for :signin_path do %>
  <%= link_to "User Sign In", new_user_session_path, {:class => "sign_in_out button dark"} %>
<%end%>

<div id="left_splash_containter">
  <img class="screenshot" src="/images/screenshot.png"/>
</div>

<h1>Where's My School Bus</h1>
<div class="splash_info">
  <h2 class="break" >Real-time school bus locations anytime, anywhere.</h1>
   <br> 
  Where’s My School Bus makes real-time bus information available online for parents and guardians in Boston Public Schools. Your student’s bus is displayed on a detailed map, showing both its recent and current location. Waiting at the stop for a late bus? Blizzard got traffic moving at a crawl? Use your smartphone or computer to instantly check the bus location. Tracking your student’s bus has never been easier, faster or more accurate.
   <br>  <br> 
  <h2 class="break">To Create an Account </h1>
   <br> 
    <h6 class="break">
      Contact the Transportation Department
       <a href="tel:+1-617-635-9520">(617) 635-9520</a>.<br>
       Monday through Friday: 
     8:30 a.m. - 5:00 p.m. </h1>
  <br>
  <ul class="list-tick">
    <li>After guardian is verified, BPS operator verbally collects email address of guardian and creates account.</li>
    <li>You will receive an email containing a link to activate your account. After signing up, guardian can track only the bus numbers in account.</li>
    <li>To edit or change the bus numbers displayed in the application, you must call BPS.</li>
  </ul>
<br>
  <%= link_to "User Sign In", new_user_session_path, {:class => "button dark right"} %>