config/routes.rb
Wheresmybus::Application.routes.draw do  
  root :to => 'application#index'

  resources :busses do
    member do
      get 'path'
    end
    collection do
      post "update_nicknames"
      get "confirm_destroy_all"
      delete "destroy_all"
    end
  end

  devise_for :admins

  devise_for :users, :controllers=>{:confirmations=>"users_confirmations"}, :skip=>:registrations do
    put "/users/confirmations", :to=>"users_confirmations#update", :as=>:update_user_confirmation
  end
  as :user do
    scope "/users" do
      resource :profile, :controller=>"registrations", :only=>[:edit,:update] do
        get "edit_password", :as=>"edit_password_of"
      end
    end
  end
  
  resources :users do
    collection do
      get "confirm_destroy_all"
      delete "destroy_all"
    end
  end
  
  get "/welcome" => "users#splash"
  

end

app/views/layouts/_notices.html.erb
<p id="notice"><%= flash[:notice] %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Where's My School Bus | Boston Public Schools</title>
  <%= stylesheet_link_tag :all %>
  <%= csrf_meta_tag %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag "nested_form" %>
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-25443807-1']);
    _gaq.push(['_setDomainName', '.heroku.com']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
</head>

<body>
  
  <div id="header">
    <div id="wmsblogo">
      <%= image_tag "wmsb.png", :alt=>"Where's My School Bus?" %>
      <% if admin_signed_in? %>
        <%= link_to "Sign Out", destroy_admin_session_path, {:class => "sign_in_out button"} %>
      <% else %>
        <% if content_for? :signin_path %>
          <%= yield :signin_path %>
        <% else %>
          <%= link_to "Administrator Sign In", new_admin_session_path, {:class => "sign_in_out button dark"} %>
        <%end%>
      <%end%>
      <div id="bps_logo"></div>
    </div>
    <a href="http://www.bostonbuilt.org/"><img class="built-in-boston" src="/images/built_in_boston_color_fancy.png"/></a>
  </div>
  
  <div id="main">
    <%= render :partial => 'layouts/notices' %>
    <div class="user_panel">
      <%= yield %>
    </div>
  </div>
  
  <div id="footer">
    Made by
    <a href="http://codeforamerica.org">Code for America</a>
    in partnership with the
    <a href="http://www.newurbanmechanics.org">City of Boston</a>
  </div>
</body>

</html>